# GENERAL CONSTANTS
BUCKET_SIZE = 0.1
TIME_NAME = "Time"
TIME_COL = 1
INFO_NAME = "Info"
INFO_COL = 6

# CONSTANTS FOR LOSS STATS
RESULT_DIR = "graphs/loss/"

# NEW GENERAL CONSTANTS
REL_TIME_COL = 0
IP_ID_COL = 1
SRC_PORT_COL = 2
DST_PORT_COL = 3
SEQ_NUM_COL = 4
ACK_NUM_COL = 5
DATA_LEN_COL = 6

MTU = 1448

CLIENT_1_PORT = 62387
SERVER_PORT = 5201

PORT_START = 62387
